### ISSUE TITLE
Regression: AppDeploymentDeleteServiceInstanceWorkflow leaks backend services on deletion

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-app-broker#344]
## Expected behavior

* As an app broker user provisioning brokered service without backing app (i.e. only backing service(s)), see #287
* in order to avoid backing service leak 
* I need backing services to be deleted when a brokered service is unprovisionned

## Observed behavior

Following #318, the AppDeploymentDeleteServiceInstanceWorkflow.deleteBackingServices() method is only attempting to delete backing services bound to applications, and hence skipping backing services when there is no associated backing services.

https://github.com/spring-cloud/spring-cloud-app-broker/blob/b0f2cbc5f4738cb0df8b5d06f3a9888c0188dc06/spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/workflow/instance/AppDeploymentDeleteServiceInstanceWorkflow.java#L75-L92

/CC @LittleBaiBai 

In addition, in case the provisioning completed with error such as the following, then this triggers a leak of backing services
   - the backing services failed to be bound to the backing applications
   - some backing services failed to be created
   - the backing application failed to starter

I understand that the following test enforces this behavior, i.e. that a non bound matching backing service instance does not get deleted upon brokered service deletion
https://github.com/spring-cloud/spring-cloud-app-broker/blob/b0f2cbc5f4738cb0df8b5d06f3a9888c0188dc06/spring-cloud-app-broker-integration-tests/src/test/java/org/springframework/cloud/appbroker/integration/DeleteInstanceWithServicesComponentTest.java#L105-L157

**Comment by gberche-orange** [comment]
I've reproduced this into unit test, and was about to submit a PR with a fix.

I'm however lacking some background on expected behavior
- @LittleBaiBai What was the intention in #318 regarding only deleting backing services bound to backing apps ? 
- What problems were causing previous behavior to attempt to delete any expected backing service (even if actually missing or unbound to the backing app) ?
- Is it a valid supported case to have multiple backing applications sharing a same backing service instance ?

**Comment by royclarkson** [comment]
The idea is that App Broker shouldn't delete anything that it didn't create or for which isn't responsible. We're happy to reconsider this.

**Comment by gberche-orange** [comment]
thanks @royclarkson 

> The idea is that App Broker shouldn't delete anything that it didn't create or for which isn't responsible. We're happy to reconsider this.

Do you mean, that the change was intended to prevent that the App Broker deletes a backing service instance which prexisted in the target space while it matches the brokered service spec (i.e. same service offering/plan/instance-name) ? 

Is this a case observed in the field which deserves specific handling ? 

If so, we could consider adding meta-data to backing services to record that the app broker provisionned the backing service, and possibly with a brokered service definition version (in case the brokered service definition changes). See related work at https://github.com/orange-cloudfoundry/osb-cmdb-spike/issues/10 which could be contributed to this goal

**Comment by royclarkson** [comment]
> If the list of backing services is updated, the default behavior is to create and bind the new backing service instances, and to unbind and delete the existing backing service instances that are no longer listed in the configuration.

The referenced change was all about updating an SI, and the above is the desired behavior. Sorry, haven't had a chance to dig through this in detail, but if you feel like it's inconsistent with the actual behavior, then we need to address it. e.g. if deleting an SI is now broken.

**Comment by gberche-orange** [comment]
>  if you feel like it's inconsistent with the actual behavior, then we need to address it. e.g. if deleting an SI is now broken.

Yes, this is my understanding that brokered service deletion is broken. I'll let you read in detail diagnostic and suggested fix above when you have available time.

Then, please let me know whether you like a PR that reverts related part of #318 (in `AppDeploymentDeleteServiceInstanceWorkflow`) and updates CT/AT accordingly (this is currently blocking #292 )

**Comment by LittleBaiBai** [comment]
@gberche-orange 

The intent of #318 was to be able to remove bound apps that are no longer listed in backing services config on `upgrade` update (see #293). The implementation was based on the assumption that backing services will always be bound to backing apps. I wasn't aware of the use case to use backing services without backing app (#287). Sorry about that. We should add a component test that reveal this regression and make it work for all use cases.

**Comment by gberche-orange** [comment]
Thanks @LittleBaiBai for your reply. 

>  I wasn't aware of the use case to use backing services without backing app (#287). Sorry about that. 
> We should add a component test that reveal this regression and make it work for all use cases.

No worries, my bad for not contributing these tests earlier as part of #287

I'm contributing them in 
[CreateInstanceWithParametersOnlyABackingServiceComponentTest.java](https://github.com/spring-cloud/spring-cloud-app-broker/pull/292/files#diff-3905712a4ef5d484678d49b0294872c7)
and an acceptance test in [CreateInstanceWithOnlyServicesAcceptanceTest.java](https://github.com/spring-cloud/spring-cloud-app-broker/pull/292/files#diff-f54f9df80b9f277033ed077d538c62fc)

**Comment by gberche-orange** [comment]
@LittleBaiBai would that make sense as a 1st step to revert the behavior of a `service instance unprovision` to the previous algorithm (i.e. delete apps and services in current config)? 

As a 2nd step, I was suggesting in https://github.com/spring-cloud/spring-cloud-app-broker/issues/344#issuecomment-600611289 to add meta-data to backing services and possible backing apps (e.g. attach the brokered service instance guid as annotation), so that all previously provisionned apps and service instance would be deleted, regardless of possibly inconsistent state (e.g. as a result of an error) or of a config update.

**Comment by gberche-orange** [comment]
@LittleBaiBai @royclarkson 

I pushed a commit which reverts of the service instance deprovisionning in b2324e4fb3edde4247071e11cc23ea8392952a1f as part of #292

Can you please have a look and provide your opinion and your review ?

**Comment by royclarkson** [comment]
@gberche-orange I'm working on a fix for this. Instead of reverting completely, the new logic will reinstate the previous functionality of deleting any configured services, however it will also delete any services bound to the deployed apps. I'm still not sure this is quite right, because @LittleBaiBai's change was really only meant to effect service instance upgrades. Hopefully will have a PR today.

**Comment by gberche-orange** [comment]
thanks @royclarkson 

Note that my osb-cmdb project is not affected anymore by this issue, but I'm sure your PR will be useful to other app broker use-cases.

> I'm still not sure this is quite right, because @LittleBaiBai's change was really only meant to effect service instance upgrades.

One way to keep track of which service instances were provisionned and to take into account provisionning errors, might be add attaching [metadata](https://docs.cloudfoundry.org/adminguide/metadata.html) to backing services/apps to link them to brokered service instances. See related comment https://github.com/spring-cloud/spring-cloud-app-broker/issues/344#issuecomment-600611289 which details a bit this idea.

**Comment by royclarkson** [comment]
@gberche-orange thanks. We may need to implement metadata or something similar like you are suggesting. It feels like a more significant change we can consider in the next major version. I appreciate all your feedback. Hopefully the project will continue to mature to a point where you can reconsider using it.
